### ISSUE TITLE
OAuth

### ISSUE THREAD

**Issue by bertocq** [consul/docs#19]
Create a section under "Features" for OAuth explanation & tips, some quick notes:

1. Configure at `config/secrets.yml` the keys for the services you want to integrate for login:
  ```yml
    twitter_key: ""
    twitter_secret: ""
    facebook_key: ""
    facebook_secret: ""
    google_oauth2_key: ""
    google_oauth2_secret: ""
  ```

2.For each service, go to it's developer platform and whenever asked for the auth urls use the following ones that `rake routes` outputs:
  ```bash
user_omniauth_authorize GET|POST /users/auth/:provider(.:format)          users/omniauth_callbacks#passthru {:provider=>/twitter|facebook|google_oauth2/}
user_omniauth_callback GET|POST /users/auth/:action/callback(.:format) users/omniauth_callbacks#(?-mix:twitter|facebook|google_oauth2)
```

**BERTO:** I'm not sure here what should be a correct example for the second url, the first example can be just `yourdomain.com/users/auth/facebook.json` ... maybe second url isn't required when setting up third party login with oauth.. just the first one I think
